services:
  - type: web
    name: hospital-management-system
    env: java
    plan: free
    region: oregon
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    build:
      env:
        - key: JAVA_HOME
          value: /opt/render/project/.render/java/openjdk-17
