services:
  - type: web
    name: hospital-management-system
    runtime: java17
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/Hospital-Management-2025-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
